eureka:
  instance:
    status-page-url-path: /swagger-ui.html
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8066/mycatdb
    username: writer
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #druid连接池
    initialSize: 1
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    validationQuery: SELECT 1 FROM DUAL
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true
    useGlobalDataSourceStat: true
  druid:
    stat:
      slowSqlMillis: 2000
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      max-wait: -1
    timeout: 0
    expireSeconds: 1800
mybatis:
  type-aliases-package: com.api.domain
  mapper-locations: classpath:mapper/*Mapper.xml
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
logging:
  config: classpath:logback.xml