eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url-path: /
turbine:
  app-config: cloud-api
  cluster-name-expression: "'default'"
  combine-host-port: true
spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
management:
  security:
    enabled: false
security:
  basic:
    enabled: false