security:
  basic:
    enabled: true
  user:
    name: config
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@127.0.0.1:8761/eureka/
  instance:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}